name: Generate Directory Index

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: generate directory index
        run: python .github/scripts/gdi.py

      - name: commit & push directory index
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add legend.json
          git commit -m "Generated directory index [skip ci]" || echo "No changes to commit"
          git push