name: Generate Directory Index

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: generate directory index
        run: python .github/scripts/gdi.py

      - name: deploy legend to pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true
          enable_jekyll: false
          publish_branch: gh-pages
          destination_dir: .